### ISSUE TITLE
Usage Help?

### ISSUE THREAD

**Issue by PeterBParker** [mkorman90/regipy#116]
Hello!

This project looks amazing! I read all of the documentation I could find on the repo, but I'm struggling with what kind of files I need to input. I'm currently trying to open the extension-less SOFTWARE file found in C:\Windows\System32\config like so:

```
from regipy.registry import RegistryHive
reg = RegistryHive('C:\Windows\System32\config\SOFTWARE')
```

I get no error on initializing reg, but when I try to use any of the functions in the readme (get_key, get_subkeys, etc.) I get different errors related to empty lists or non-existent functions. I'm guessing that I'm giving the function invalid input, so I'm wondering is there support in this project for those types of files and if so which function should I use?

Thanks in advance!

**Comment by tincho9** [comment]
Regipy was built for parsing of offline registry hives. The live SOFTWARE hive in the machine is locked by the operating system. You need to copy it using rawcopy or some similar tool before parsing it with Regipy.
