### ISSUE TITLE
Max size of key

### ISSUE THREAD

**Issue by HexRoman** [mkorman90/regipy#151]
Using the tool, I see that the returned `data` size of a key is always no more than 128 characters, even with keys that longer than this. 

I assured that the length is more than 128 both with the windows registry viewer and in hivexsh. 

Is there an explanation for this?

**Comment by tincho9** [comment]
Can you give me an example with a hive? I'll take a look the close weekend, Thanks.

**Comment by HexRoman** [comment]
Found that the problem is that the as_json parameter was set as True, and it is limited by this size in the code. 

Why does this limitation exist?

**Comment by tincho9** [comment]
It was in order to prevent huge values in the JSON file. I'll rethink if this is the default behavior it should have.
