### ISSUE TITLE
Making a lightweight version wheel with fewer deps

### ISSUE THREAD

**Issue by pombredanne** [mkorman90/regipy#172]
Hi:
We are adding regipy to https://github.com/nexB/scancode-toolkit and use it as a library there.
Would you be open to have a lightweight wheel version with fewer deps for use as a library?
That would be super useful!

**Comment by tincho9** [comment]
PR Looks good, what changes are left for it to be ready? Can I help somehow?

**Comment by pombredanne** [comment]
@tincho9 nothing left needed IMHO, it was more to ensure that you could have a good look at it first

**Comment by tincho9** [comment]
Thanks for everything!
I think we can close all issues. right?
