### ISSUE TITLE
Question: why apply  "inflection.underscore" on registry keys?

### ISSUE THREAD

**Issue by pombredanne** [mkorman90/regipy#176]
I see that `from inflection import underscore` is used in a few places like here https://github.com/mkorman90/regipy/blob/a796e00e8e71d8c1096df89d2a394abbf9cc26cc/regipy/plugins/software/last_logon.py#L28 to "snake-ify" the registry keys name.
What's the rationale to make this transformation?

**Comment by tincho9** [comment]
The plugins output is usually analyzed as is, and last_known_device_name (for example) is easier on the eyes than LastKnownDeviceName.
