### ISSUE TITLE
Release `2.0.1` seems to have failed to deploy

### ISSUE THREAD

**Issue by ravenexp** [mkorman90/regipy#184]
On the release page
https://github.com/mkorman90/regipy/releases/tag/2.0.1

The package download link
https://github.com/mkorman90/regipy/releases/download/2.0.1/regipy-2.0.1.tar.gz
and the source archive link
https://github.com/mkorman90/regipy/archive/refs/tags/2.0.1.tar.gz
contain different versions of the source tree.

Compare `_setup_logging()` definitions from `utils.py`:
the source archive has PR #180 applied, while the download artifact does not.

The version uploaded to PyPI also does not have the patch applied even though it's tagged as `2.0.1`.

**Comment by tincho9** [comment]
Sorry, 2.0.2 should be ok. Let me know?
https://github.com/mkorman90/regipy/releases/tag/2.0.2

**Comment by ravenexp** [comment]
Yes, 2.0.2 works as expected.
