### ISSUE TITLE
registry-dump missing some (default) values

### ISSUE THREAD

**Issue by oldmande** [mkorman90/regipy#196]
same SYSTEM registry hive as in the registry-transaction-log issue

$ registry-dump -o system.dump SYSTEM
$ grep 83da6326 system.dump  | grep 2d7ae1ff
{"subkey_name":"0003","path":"\\ControlSet001\\Enum\\USB\\VID_80EE&PID_0021\\5&2d7ae1ff&0&1\\Properties\\{83da6326-97a6-4088-9453-a1923f573b29}\\0003","timestamp":"2015-12-12T02:18:32.065852+00:00","values_count":0,"values":[],"actual_path":null}
{"subkey_name":"000A","path":"\\ControlSet001\\Enum\\USB\\VID_80EE&PID_0021\\5&2d7ae1ff&0&1\\Properties\\{83da6326-97a6-4088-9453-a1923f573b29}\\000A","timestamp":"2015-12-12T02:18:31.847936+00:00","values_count":0,"values":[],"actual_path":null}
{"subkey_name":"0064","path":"\\ControlSet001\\Enum\\USB\\VID_80EE&PID_0021\\5&2d7ae1ff&0&1\\Properties\\{83da6326-97a6-4088-9453-a1923f573b29}\\0064","timestamp":"2015-12-12T02:18:32.065852+00:00","values_count":0,"values":[],"actual_path":null}
{"subkey_name":"0065","path":"\\ControlSet001\\Enum\\USB\\VID_80EE&PID_0021\\5&2d7ae1ff&0&1\\Properties\\{83da6326-97a6-4088-9453-a1923f573b29}\\0065","timestamp":"2015-12-12T02:18:32.065852+00:00","values_count":0,"values":[],"actual_path":null}
{"subkey_name":"0066","path":"\\ControlSet001\\Enum\\USB\\VID_80EE&PID_0021\\5&2d7ae1ff&0&1\\Properties\\{83da6326-97a6-4088-9453-a1923f573b29}\\0066","timestamp":"2015-12-12T03:26:35.106732+00:00","values_count":0,"values":[],"actual_path":null}
{"subkey_name":"{83da6326-97a6-4088-9453-a1923f573b29}","path":"\\ControlSet001\\Enum\\USB\\VID_80EE&PID_0021\\5&2d7ae1ff&0&1\\Properties\\{83da6326-97a6-4088-9453-a1923f573b29}","timestamp":"2015-12-12T02:18:32.065852+00:00","values_count":0,"values":[],"actual_path":null}

![RegistryExplorer_SYSTEM_view](https://user-images.githubusercontent.com/90158285/132425855-1be2714a-dab0-4a1e-8d9e-9919c61372d4.png)

**Comment by tincho9** [comment]
Hi, Can you share the sample?

**Comment by oldmande** [comment]
that looks correct.

thanks.

**Comment by tincho9** [comment]
Everything looks ok? Can I close this issue?

**Comment by oldmande** [comment]
yes.

**Comment by oldmande** [comment]
I think so,  let me fire up my VM and take a closer look.

thanks,
John
________________________________
From: tincho9 ***@***.***>
Sent: Tuesday, May 17, 2022 4:04 AM
To: mkorman90/regipy ***@***.***>
Cc: Ormonde, John ***@***.***>; Author ***@***.***>
Subject: [External] Re: [mkorman90/regipy] registry-dump missing some (default) values (#196)


This message is from an EXTERNAL SENDER - be CAUTIOUS of links and attachments. THINK BEFORE YOU CLICK.
________________________________


Hi, these values were of a value type name DEVPROP ()... I actually had a plan to parse these structure and never got to it.
My solution for now is to try and dump these values as strings - #214<https://github.com/mkorman90/regipy/pull/214>
For example:

[image]<https://user-images.githubusercontent.com/18242935/168761056-9b1b740f-7d99-4be8-88a3-7f9b7d0e1eab.png>

Is this the expected output?
