### ISSUE TITLE
Cant't decode value

### ISSUE THREAD

**Issue by opliyal3** [mkorman90/regipy#210]
both with using: registry-dump.exe SAM.hiv -o test.json and Python [for entry in reg.recurse_subkeys(as_json=True):]

always see like this

![image](https://user-images.githubusercontent.com/30455352/160813361-f9eb9586-63d4-4be4-a8d6-ad0daf848b0a.png)

**Comment by tincho9** [comment]
Hi, Do you know what is the original value? Did you manage to decode it with other tools?
