### ISSUE TITLE
Publish wheel on PyPI for 2.3.1

### ISSUE THREAD

**Issue by pombredanne** [mkorman90/regipy#213]
Hi: you may not have (yet) pushed a wheel to PyPI for 2.3.1?
If you care I could help with a script (for instance a simple GitHub action)to automate this whenever you tag your repo?

**Comment by tincho9** [comment]
Hi, I'm going to automate it soon, Added the wheel of 2.3.2 to its release page
https://github.com/mkorman90/regipy/releases/tag/2.3.2
