### ISSUE TITLE
Support Wine registry

### ISSUE THREAD

**Issue by KOLANICH** [mkorman90/regipy#247]
It turns out Wine registry format differs somehow from Windows one.

**Comment by mkorman90** [comment]
What do you mean Wine registry? Do you have a sample?

**Comment by KOLANICH** [comment]
>What do you mean Wine registry?

Wine is a compatibility layer allowing run some Windows apps in POSIX OSes. It has an own registry that is accessed using the same API as in Windows and is stored within Wine prefix (a dir Wine stores the files/dirs of a virtual Windows system, `~/.wine` by default).

My use case is: I need to discover some files of some Windows software. I have a standalone library in Python capable reading them. In order to do it I look up where this software is installed from the registry. On Windows I use `winreg` from python standard library. On Linux (using linux native python binary, not the Windows one that is run in Wine) I am going to read the info from the registry in default Wine prefix.

>Do you have a sample?

`williballenthin` has found one in https://github.com/williballenthin/python-registry/issues/106 . It turns out the format is the textual one, so it may be out of scope of this and the other project.
