### ISSUE TITLE
regipy-cli: Logging: Use STDINFO instead of STDOUT for information, warning and error messages

### ISSUE THREAD

**Issue by tbi360** [mkorman90/regipy#255]
Hi there, thanks for this tool, I find it very useful.

The tool outputs logging to STDOUT by default. When processing stdout, info messages from logging breaks the JSON stream. Would it be possible to switch to STDINFO logging to preserve the integrity of the STDOUT data stream?

Many thanks,

Tom

**Comment by mkorman90** [comment]
Fixed in https://github.com/mkorman90/regipy/pull/259
