### ISSUE TITLE
Subkey not listed although it exist

### ISSUE THREAD

**Issue by cats-coder** [mkorman90/regipy#64]
When trying to access `reg.get_key(r"System\ControlSet001\Control\hivelist")` it raises a `RegistryKeyNotFound` Error. When opening the specified Hive file with Regedit.exe i can see this "hivelist" key though (HKLM\System\ControlSet001\Control\hivelist) and view it's values.

Printing all subkeys of `System\ControlSet001\Control` with `reg.get_key(r"System\ControlSet001\Control").iter_subkeys()` it look like all keys are there except "hivelist". It's just missing. 

Not sure if this is a bug or actually expected behavior.

**Comment by tincho9** [comment]
I'm pretty sure this is a volatile key, because I do not see it with any other tool I've tested, except when using regedit on a live machine.

**Comment by cats-coder** [comment]
Ah, well that would explain it. Although i would expect this kind of registry key to persist over reboot.
