### ISSUE TITLE
Keys do not match due to case sensitivity

### ISSUE THREAD

**Issue by cats-coder** [mkorman90/regipy#69]
When trying to open the key `System\<CurrentControlSet>\Services\Tcpip` from a Win10 SYSTEM hive it works fine. However, when trying to open the same key from a Windows Server SYSTEM hive this will fail.

In this case `Services` was named `services`, so to open the key i had to use `System\<CurrentControlSet>\services\Tcpip`.

I would expect `services` to match `Services` and vice versa. My workaround so far is to check for both keys with try-catch but that seems dirty and i might miss alot of cases. Maybe there is an alternative?

**Comment by tincho9** [comment]
#70 should solve it, thanks @Cr4ckC4t
