### ISSUE TITLE
try_decode_binary applying max_len when as_json=False

### ISSUE THREAD

**Issue by pukhanov** [mkorman90/regipy#78]
It appears that try_decode_binary applies the max_len to the data regardless off whether as_json is set or not. This causes data to be truncated when using something like get_values with as_json=False

**Comment by tincho9** [comment]
@pukhanov Please tell me if this fixes the issue.

**Comment by pukhanov** [comment]
Looking at the change, line 148 should have ``[:max_len]`` removed and then line 153, should be wrapped in ``if as_json:``

**Comment by tincho9** [comment]
Should be ok now

**Comment by pukhanov** [comment]
Looks good, thanks.
