### ISSUE TITLE
Parse all hives and retrieve json

### ISSUE THREAD

**Issue by garanews** [mkorman90/regipy#93]
Hi, 
it would pe possible use regipy as library to parse recursively all windows hive and get json of each hive?

**Comment by tincho9** [comment]
You mean parsing the hives on a live system? Because Regipy is only for offline hives.

**Comment by garanews** [comment]
offline, extracted from memory dump :)

**Comment by tincho9** [comment]
You can use this function: 
https://github.com/mkorman90/regipy/blob/9fb471fd7aa33940b6df3087abb89992f7d341f2/regipy/plugins/utils.py#L9

The first parameter would have to be a registry hive instance initiated like this: 

```
registry_hive = RegistryHive('/tmp/ntuser.dat')
dump_hive_to_json(registry_hive, '/tmp/parsed_ntuser.json')
```

**Comment by garanews** [comment]
I will try thanks.
Just seen that release on github is stop at 1.5.2 (and has some installation issue), instead on pypi there is the 1.6.3 and installation works.

**Comment by tincho9** [comment]
I'm closing this, let me know if you need more help.
